domain: contract-first-idp
system: default-application
component: default-service
deployment: jvm

git:
  host: github.com
  branch: main

image:
  registry: image-registry.openshift-image-registry.svc:5000
