domain: contract-first-idp
system: default-application
component: default-service
groupid: com.redhat

git:
  host: github.com
  branch: main

apicurioRegistry: apicurio-registry.apicurio-registry.router-default.apps.cluster-56dmd.56dmd
mockRegistry: microcks-microcks.apps.cluster-56dmd.56dmd.sandbox2864.opentlc.com

image:
  registry: image-registry.openshift-image-registry.svc:5000
